#!/bin/bash
# MCP Marketplace Demo Commands
# This script demonstrates the available commands

echo "==================================="
echo "MCP Marketplace - Command Examples"
echo "==================================="
echo ""

echo "1. SEARCH & DISCOVERY"
echo "--------------------"
echo "# Search for filesystem servers"
echo "swarm-cli mcp search filesystem"
echo ""
echo "# Search by tag"
echo "swarm-cli mcp search --tag database"
echo ""
echo "# Show server details"
echo "swarm-cli mcp info github"
echo ""
echo "# Interactive marketplace"
echo "swarm-cli mcp marketplace"
echo ""

echo "2. INSTALLATION"
echo "---------------"
echo "# Install a server"
echo "swarm-cli mcp install filesystem"
echo ""
echo "# Install specific version"
echo "swarm-cli mcp install github --version 2.0.0"
echo ""
echo "# Install globally"
echo "swarm-cli mcp install postgres --global"
echo ""

echo "3. CONFIGURATION"
echo "----------------"
echo "# Interactive configuration"
echo "swarm-cli mcp config github"
echo ""
echo "# Test connection"
echo "swarm-cli mcp test github"
echo ""

echo "4. MANAGEMENT"
echo "-------------"
echo "# List installed servers"
echo "swarm-cli mcp list"
echo ""
echo "# Update a server"
echo "swarm-cli mcp update github"
echo ""
echo "# Update all servers"
echo "swarm-cli mcp update --all"
echo ""
echo "# Check for updates"
echo "swarm-cli mcp update --check"
echo ""
echo "# Uninstall a server"
echo "swarm-cli mcp remove filesystem"
echo ""

echo "5. REGISTRY MANAGEMENT"
echo "----------------------"
echo "# Update registry"
echo "swarm-cli mcp registry update"
echo ""
echo "# Show statistics"
echo "swarm-cli mcp registry stats"
echo ""
echo "# List tags"
echo "swarm-cli mcp registry tags"
echo ""

echo "6. VERSION MANAGEMENT"
echo "---------------------"
echo "# View changelog"
echo "swarm-cli mcp changelog github"
echo ""
echo "# Pin version"
echo "swarm-cli mcp pin github 1.5.0"
echo ""

echo "==================================="
echo "For more information, see:"
echo "src/mcp/marketplace/README.md"
echo "==================================="
