/**
 * STATE.md Parser
 *
 * Parses STATE.md files with YAML frontmatter and markdown sections.
 * Converts between STATE.md text and structured State objects.
 */

import YAML from 'yaml';
import {
  State,
  StateFrontmatter,
  StateSection,
  StateItem,
  StateSectionType,
  StatePriority,
  CellStatus,
  CellType,
  ParserOptions,
} from './types';

/**
 * Error thrown when parsing fails
 */
export class ParseError extends Error {
  constructor(message: string, public readonly line?: number) {
    super(message);
    this.name = 'ParseError';
  }
}

/**
 * Default parser options
 */
const DEFAULT_OPTIONS: ParserOptions = {
  strict: false,
  allowUnknownSections: true,
};

/**
 * Parse STATE.md content into structured State object
 */
export function parseState(content: string, options: ParserOptions = {}): State {
  const opts = { ...DEFAULT_OPTIONS, ...options };

  // Split frontmatter and content
  const { frontmatter, body } = splitFrontmatter(content);

  // Parse frontmatter
  const parsedFrontmatter = parseFrontmatter(frontmatter);

  // Parse sections
  const sections = parseSections(body, opts);

  return {
    frontmatter: parsedFrontmatter,
    sections,
    rawContent: body.trim(),
  };
}

/**
 * Split content into frontmatter and body
 */
function splitFrontmatter(content: string): { frontmatter: string; body: string } {
  const trimmed = content.trim();

  // Check for YAML frontmatter (starts with ---)
  if (!trimmed.startsWith('---')) {
    return { frontmatter: '', body: content };
  }

  const endMatch = trimmed.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
  if (!endMatch) {
    return { frontmatter: '', body: content };
  }

  return {
    frontmatter: endMatch[1],
    body: endMatch[2],
  };
}

/**
 * Parse YAML frontmatter
 */
function parseFrontmatter(yamlContent: string): StateFrontmatter {
  if (!yamlContent.trim()) {
    throw new ParseError('Missing YAML frontmatter');
  }

  try {
    const parsed = YAML.parse(yamlContent) as Partial<StateFrontmatter>;

    // Validate required fields
    if (!parsed.version) {
      throw new ParseError('Missing required field in frontmatter: version');
    }
    if (!parsed.project) {
      throw new ParseError('Missing required field in frontmatter: project');
    }

    // Extract known fields and put the rest in metadata
    const { version, project, lastSync, autoGenerated, metadata = {}, ...rest } = parsed;

    return {
      version: version as '1.0',
      project: project,
      lastSync: lastSync,
      autoGenerated: autoGenerated ?? false,
      metadata: { ...metadata, ...rest },
    };
  } catch (error) {
    if (error instanceof ParseError) throw error;
    throw new ParseError(`Failed to parse YAML frontmatter: ${(error as Error).message}`);
  }
}

/**
 * Parse markdown body into sections
 */
function parseSections(body: string, options: ParserOptions): StateSection[] {
  const sections: StateSection[] = [];
  const lines = body.split('\n');

  let currentSection: { type: StateSectionType; title?: string; content: string[] } | null = null;
  let order = 0;

  for (const line of lines) {
    const sectionMatch = line.match(/^##\s+(.+)$/);

    if (sectionMatch) {
      // Save previous section
      if (currentSection) {
        sections.push({
          type: currentSection.type,
          title: currentSection.title,
          items: parseSectionContent(currentSection.content.join('\n'), currentSection.type, options),
          order: order++,
        });
      }

      // Start new section
      const sectionTitle = sectionMatch[1].trim();
      currentSection = {
        type: inferSectionType(sectionTitle),
        title: sectionTitle,
        content: [],
      };
    } else if (currentSection) {
      currentSection.content.push(line);
    }
  }

  // Save last section
  if (currentSection) {
    sections.push({
      type: currentSection.type,
      title: currentSection.title,
      items: parseSectionContent(currentSection.content.join('\n'), currentSection.type, options),
      order: order++,
    });
  }

  return sections;
}

/**
 * Infer section type from title
 */
function inferSectionType(title: string): StateSectionType {
  const lower = title.toLowerCase();

  if (lower.includes('overview') || lower.includes('summary')) return 'overview';
  if (lower.includes('active') || lower.includes('in progress') || lower.includes('doing')) return 'active';
  if (lower.includes('completed') || lower.includes('done') || lower.includes('finished')) return 'completed';
  if (lower.includes('blocked') || lower.includes('stuck') || lower.includes('waiting')) return 'blocked';
  if (lower.includes('backlog') || lower.includes('todo') || lower.includes('pending')) return 'backlog';
  if (lower.includes('meta') || lower.includes('info')) return 'metadata';

  return 'custom';
}

/**
 * Parse section content into items
 */
function parseSectionContent(content: string, sectionType: StateSectionType, options: ParserOptions): StateItem[] {
  const items: StateItem[] = [];
  const lines = content.split('\n');

  let currentItem: Partial<StateItem> | null = null;
  let currentNotes: string[] = [];
  let itemLines: string[] = [];

  function saveCurrentItem() {
    if (currentItem) {
      items.push({
        ...currentItem,
        notes: currentNotes.length > 0 ? currentNotes : undefined,
      } as StateItem);
    }
    currentItem = null;
    currentNotes = [];
    itemLines = [];
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Check for item line (- [ ] or - [x] or - ID:)
    const itemMatch = trimmed.match(/^-\s+\[([\s\w])\]\s*(.+)$/) ||
                      trimmed.match(/^-\s+\*\*(.+?)\*\*:\s*(.+)$/) ||
                      trimmed.match(/^-\s+`([^`]+)`:\s*(.+)$/);

    if (itemMatch) {
      saveCurrentItem();

      if (itemMatch[1].length === 1 && ' xX'.includes(itemMatch[1])) {
        // Checkbox format: - [ ] or - [x]
        const status = itemMatch[1].trim() ? 'completed' : inferStatusFromSection(sectionType);
        const content = itemMatch[2].trim();

        // Try to extract ID from title: **ID**: title or `ID`: title
        const idMatch = content.match(/^\*\*(.+?)\*\*:\s*(.+)$/) ||
                        content.match(/^`([^`]+)`:\s*(.+)$/);
        if (idMatch) {
          currentItem = {
            id: idMatch[1].trim(),
            title: idMatch[2].trim(),
            status: status as CellStatus,
          };
        } else {
          currentItem = { title: content, status: status as CellStatus };
        }
      } else {
        // ID format: - **ID**: Title or - `ID`: Title
        const id = itemMatch[1].trim();
        const title = itemMatch[2].trim();
        currentItem = { id, title, status: inferStatusFromSection(sectionType) as CellStatus };
      }
    } else if (trimmed.startsWith('- ') && !currentItem) {
      // Simple list item without checkbox or ID
      const title = trimmed.substring(2).trim();
      currentItem = {
        title,
        status: inferStatusFromSection(sectionType) as CellStatus,
      };
    } else if (currentItem && line.startsWith('  ')) {
      // Indented line - could be notes or metadata
      const indentContent = line.substring(2).trim();

      // Check for key-value pairs
      const kvMatch = indentContent.match(/^(\w+):\s*(.+)$/);
      if (kvMatch) {
        const originalKey = kvMatch[1];
        const lowerKey = originalKey.toLowerCase();
        let value = kvMatch[2].trim();
        // Strip surrounding quotes if present
        if ((value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))) {
          value = value.slice(1, -1);
        }
        parseItemField(currentItem, lowerKey, value, originalKey);
      } else if (indentContent) {
        currentNotes.push(indentContent);
      }
    } else if (trimmed === '' && currentItem) {
      // Empty line - might be end of item
      if (i + 1 < lines.length && !lines[i + 1].trim().startsWith('- ')) {
        // Next line is not a new item, treat as continuation
        continue;
      }
      saveCurrentItem();
    }

    itemLines.push(line);
  }

  saveCurrentItem();

  // Generate IDs for items without them
  items.forEach((item, index) => {
    if (!item.id) {
      item.id = generateItemId(item, index);
    }
  });

  return items;
}

/**
 * Parse an item field from key-value string
 */
function parseItemField(item: Partial<StateItem>, key: string, value: string, originalKey?: string): void {
  switch (key) {
    case 'id':
      item.id = value;
      break;
    case 'status':
      item.status = value as CellStatus;
      break;
    case 'type':
      item.type = value as CellType;
      break;
    case 'priority':
      item.priority = value.toLowerCase() as StatePriority;
      break;
    case 'owner':
      item.owner = value;
      break;
    case 'parent':
    case 'parentid':
      item.parentId = value;
      break;
    case 'tags':
      item.tags = value.split(',').map(t => t.trim());
      break;
    case 'created':
    case 'createdat':
      item.createdAt = value;
      break;
    case 'updated':
    case 'updatedat':
      item.updatedAt = value;
      break;
    case 'completed':
    case 'completedat':
      item.completedAt = value;
      break;
    case 'blocked':
    case 'blockedreason':
      item.blockedReason = value;
      break;
    default:
      // Store in metadata using original key case
      if (!item.metadata) item.metadata = {};
      item.metadata[originalKey || key] = value;
  }
}

/**
 * Infer status from section type
 */
function inferStatusFromSection(sectionType: StateSectionType): CellStatus {
  switch (sectionType) {
    case 'active':
      return 'in_progress';
    case 'completed':
      return 'completed';
    case 'blocked':
      return 'blocked';
    case 'backlog':
    case 'overview':
    default:
      return 'open';
  }
}

/**
 * Generate an ID for an item
 */
function generateItemId(item: Partial<StateItem>, index: number): string {
  if (item.title) {
    const slug = item.title
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 30);
    return `${item.type || 'task'}-${slug}-${index}`;
  }
  return `${item.type || 'task'}-${Date.now()}-${index}`;
}

/**
 * Serialize State object to STATE.md format
 */
export function serializeState(state: State): string {
  const lines: string[] = [];

  // Frontmatter
  lines.push('---');
  lines.push(YAML.stringify({
    version: state.frontmatter.version,
    project: state.frontmatter.project,
    lastSync: state.frontmatter.lastSync || new Date().toISOString(),
    autoGenerated: state.frontmatter.autoGenerated,
    ...state.frontmatter.metadata,
  }).trim());
  lines.push('---');
  lines.push('');

  // Sections
  const sortedSections = [...state.sections].sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  for (const section of sortedSections) {
    const title = section.title || formatSectionTitle(section.type);
    lines.push(`## ${title}`);
    lines.push('');

    if (section.items.length === 0) {
      lines.push('_No items_');
      lines.push('');
      continue;
    }

    for (const item of section.items) {
      lines.push(...serializeItem(item));
    }

    lines.push('');
  }

  return lines.join('\n').trim() + '\n';
}

/**
 * Serialize a single item to markdown lines
 */
function serializeItem(item: StateItem): string[] {
  const lines: string[] = [];

  // Main line with checkbox
  const checkbox = item.status === 'completed' ? '[x]' : '[ ]';
  lines.push(`- ${checkbox} **${item.id}**: ${item.title}`);

  // Metadata fields (indented)
  if (item.type) {
    lines.push(`  type: ${item.type}`);
  }
  if (item.status && item.status !== 'open') {
    lines.push(`  status: ${item.status}`);
  }
  if (item.priority) {
    lines.push(`  priority: ${item.priority}`);
  }
  if (item.owner) {
    lines.push(`  owner: ${item.owner}`);
  }
  if (item.parentId) {
    lines.push(`  parent: ${item.parentId}`);
  }
  if (item.tags && item.tags.length > 0) {
    lines.push(`  tags: ${item.tags.join(', ')}`);
  }
  if (item.createdAt) {
    lines.push(`  created: ${item.createdAt}`);
  }
  if (item.updatedAt) {
    lines.push(`  updated: ${item.updatedAt}`);
  }
  if (item.completedAt) {
    lines.push(`  completed: ${item.completedAt}`);
  }
  if (item.blockedReason) {
    lines.push(`  blocked: ${item.blockedReason}`);
  }

  // Additional metadata
  if (item.metadata) {
    for (const [key, value] of Object.entries(item.metadata)) {
      if (value !== undefined && value !== null) {
        lines.push(`  ${key}: ${value}`);
      }
    }
  }

  // Notes
  if (item.notes && item.notes.length > 0) {
    for (const note of item.notes) {
      lines.push(`  > ${note}`);
    }
  }

  return lines;
}

/**
 * Format section type as title
 */
function formatSectionTitle(type: StateSectionType): string {
  switch (type) {
    case 'overview': return 'Overview';
    case 'active': return 'Active';
    case 'completed': return 'Completed';
    case 'blocked': return 'Blocked';
    case 'backlog': return 'Backlog';
    case 'metadata': return 'Metadata';
    case 'custom': return 'Items';
    default: return String(type).charAt(0).toUpperCase() + String(type).slice(1);
  }
}

/**
 * Extract items from all sections
 */
export function extractAllItems(state: State): StateItem[] {
  return state.sections.flatMap(section => section.items);
}

/**
 * Find item by ID
 */
export function findItemById(state: State, id: string): StateItem | undefined {
  for (const section of state.sections) {
    const item = section.items.find(i => i.id === id);
    if (item) return item;
  }
  return undefined;
}

/**
 * Update or add an item in the state
 */
export function upsertItem(state: State, item: StateItem): State {
  const newState = { ...state };
  newState.sections = state.sections.map(section => ({
    ...section,
    items: [...section.items],
  }));

  // Find existing item
  for (const section of newState.sections) {
    const index = section.items.findIndex(i => i.id === item.id);
    if (index !== -1) {
      section.items[index] = item;
      return newState;
    }
  }

  // Add to appropriate section based on status
  const targetSection = newState.sections.find(s =>
    (s.type === 'active' && item.status === 'in_progress') ||
    (s.type === 'completed' && item.status === 'completed') ||
    (s.type === 'blocked' && item.status === 'blocked') ||
    (s.type === 'backlog' && item.status === 'open')
  );

  if (targetSection) {
    targetSection.items.push(item);
  } else {
    // Add to first section or create backlog
    if (newState.sections.length > 0) {
      newState.sections[0].items.push(item);
    } else {
      newState.sections.push({
        type: 'backlog',
        items: [item],
        order: 0,
      });
    }
  }

  return newState;
}

/**
 * Remove item from state
 */
export function removeItem(state: State, id: string): State {
  const newState = { ...state };
  newState.sections = state.sections.map(section => ({
    ...section,
    items: section.items.filter(i => i.id !== id),
  }));
  return newState;
}
