/**
 * STATE.md - Project State Single Source of Truth
 *
 * Types and interfaces for parsing, validating, and syncing STATE.md files.
 */

import type { CellData, CellStatus, CellType } from '../hive/types';

// Re-export types from Hive for convenience
export type { CellStatus, CellType } from '../hive/types';

/**
 * Valid state file versions for migration support
 */
export type StateVersion = '1.0';

/**
 * Priority levels for state sections
 */
export type StatePriority = 'critical' | 'high' | 'medium' | 'low';

/**
 * Section types in STATE.md
 */
export type StateSectionType =
  | 'overview'
  | 'active'
  | 'completed'
  | 'blocked'
  | 'backlog'
  | 'metadata'
  | 'custom';

/**
 * Individual task/item within a state section
 */
export interface StateItem {
  /** Unique identifier (matches Hive cell ID) */
  id: string;
  /** Task title/description */
  title: string;
  /** Current status */
  status: CellStatus;
  /** Type of work item */
  type?: CellType;
  /** Priority level */
  priority?: StatePriority;
  /** Assigned owner/agent */
  owner?: string;
  /** Parent item ID for hierarchy */
  parentId?: string;
  /** Child item IDs */
  children?: string[];
  /** Tags for categorization */
  tags?: string[];
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
  /** Completion timestamp */
  completedAt?: string;
  /** Blocked reason (if status is blocked) */
  blockedReason?: string;
  /** Additional metadata */
  metadata?: Record<string, unknown>;
  /** Notes/comments */
  notes?: string[];
}

/**
 * Section within STATE.md containing related items
 */
export interface StateSection {
  /** Section type */
  type: StateSectionType;
  /** Section title (for custom sections) */
  title?: string;
  /** Items in this section */
  items: StateItem[];
  /** Section metadata */
  metadata?: Record<string, unknown>;
  /** Section order for display */
  order?: number;
}

/**
 * YAML frontmatter in STATE.md
 */
export interface StateFrontmatter {
  /** Schema version */
  version: StateVersion;
  /** Project name */
  project: string;
  /** Last sync timestamp with Hive */
  lastSync?: string;
  /** Auto-generated flag */
  autoGenerated?: boolean;
  /** Custom metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Complete STATE.md structure
 */
export interface State {
  /** YAML frontmatter */
  frontmatter: StateFrontmatter;
  /** Content sections */
  sections: StateSection[];
  /** Raw markdown content (excluding frontmatter) */
  rawContent?: string;
}

/**
 * Validation error severity
 */
export type ValidationSeverity = 'error' | 'warning' | 'info';

/**
 * Individual validation issue
 */
export interface ValidationIssue {
  /** Error severity */
  severity: ValidationSeverity;
  /** Error message */
  message: string;
  /** Path to the issue (e.g., 'frontmatter.version', 'sections[0].items[1].id') */
  path: string;
  /** Suggested fix */
  suggestion?: string;
}

/**
 * Validation result
 */
export interface ValidationResult {
  /** Whether validation passed */
  valid: boolean;
  /** List of issues found */
  issues: ValidationIssue[];
  /** Error count */
  errorCount: number;
  /** Warning count */
  warningCount: number;
  /** Info count */
  infoCount: number;
}

/**
 * Sync direction
 */
export type SyncDirection = 'to-hive' | 'from-hive' | 'bidirectional';

/**
 * Sync operation result
 */
export interface SyncResult {
  /** Whether sync succeeded */
  success: boolean;
  /** Direction that was performed */
  direction: SyncDirection;
  /** Items synced to Hive */
  syncedToHive: number;
  /** Items synced from Hive */
  syncedFromHive: number;
  /** Conflicts detected */
  conflicts: SyncConflict[];
  /** Error message if failed */
  error?: string;
  /** Timestamp of sync */
  timestamp: string;
}

/**
 * Sync conflict between STATE.md and Hive
 */
export interface SyncConflict {
  /** Item ID with conflict */
  itemId: string;
  /** Field that conflicts */
  field: string;
  /** Value in STATE.md */
  stateValue: unknown;
  /** Value in Hive */
  hiveValue: unknown;
  /** Resolution chosen */
  resolution?: 'state' | 'hive' | 'manual';
}

/**
 * Parser options
 */
export interface ParserOptions {
  /** Strict parsing mode */
  strict?: boolean;
  /** Allow unknown sections */
  allowUnknownSections?: boolean;
  /** Custom section parsers */
  customParsers?: Record<string, (content: string) => StateItem[]>;
}

/**
 * State manager configuration
 */
export interface StateManagerConfig {
  /** Path to STATE.md file */
  stateFilePath: string;
  /** Hive storage configuration */
  hiveConfig?: {
    baseDir?: string;
    enableGit?: boolean;
    autoCommit?: boolean;
  };
  /** Auto-sync on changes */
  autoSync?: boolean;
  /** Validation rules */
  validation?: {
    requireAllFields?: boolean;
    strictTypes?: boolean;
  };
}

/**
 * Default configuration
 */
export const DEFAULT_STATE_CONFIG: StateManagerConfig = {
  stateFilePath: './STATE.md',
  hiveConfig: {
    baseDir: '.hive',
    enableGit: true,
    autoCommit: true,
  },
  autoSync: false,
  validation: {
    requireAllFields: false,
    strictTypes: true,
  },
};

/**
 * CLI command options
 */
export interface StateCliOptions {
  /** STATE.md file path */
  file?: string;
  /** Output format */
  format?: 'json' | 'table' | 'yaml';
  /** Filter by status */
  status?: CellStatus;
  /** Filter by type */
  type?: CellType;
  /** Filter by owner */
  owner?: string;
  /** Show verbose output */
  verbose?: boolean;
}

/**
 * Diff result between two states
 */
export interface StateDiff {
  /** Added items */
  added: StateItem[];
  /** Removed items */
  removed: StateItem[];
  /** Modified items (with field changes) */
  modified: {
    item: StateItem;
    changes: { field: string; oldValue: unknown; newValue: unknown }[];
  }[];
  /** Unchanged items */
  unchanged: StateItem[];
}

/**
 * Export format options
 */
export type ExportFormat = 'json' | 'yaml' | 'csv' | 'markdown';

/**
 * State statistics
 */
export interface StateStats {
  /** Total items */
  total: number;
  /** Items by status */
  byStatus: Record<CellStatus, number>;
  /** Items by type */
  byType: Record<string, number>;
  /** Items by section */
  bySection: Record<string, number>;
  /** Items by owner */
  byOwner: Record<string, number>;
  /** Last updated timestamp */
  lastUpdated: string | null;
}
