import { GitHubClient, GitHubIssue } from './github-client';
import { Logger } from '../utils/logger';

const logger = new Logger('IssueSync');

export interface Task {
  id: string;
  title: string;
  description: string;
  status: 'pending' | 'in_progress' | 'completed';
  githubIssueId?: number;
}

export interface Spec {
  title: string;
  description: string;
  tasks: Task[];
}

export class IssueSync {
  constructor(private client: GitHubClient) {}

  async createIssuesFromSpec(
    spec: Spec,
    owner: string,
    repo: string,
    labels?: string[]
  ): Promise<Task[]> {
    logger.info(`Creating ${spec.tasks.length} issues from spec: ${spec.title}`);
    
    const updatedTasks: Task[] = [];
    
    for (const task of spec.tasks) {
      const body = this.formatTaskBody(task, spec);
      
      try {
        const issue = await this.client.createIssue(
          owner,
          repo,
          task.title,
          body,
          labels
        );
        
        updatedTasks.push({
          ...task,
          githubIssueId: issue.number
        });
        
        logger.info(`Created issue #${issue.number} for task: ${task.title}`);
      } catch (error) {
        logger.error(`Failed to create issue for task: ${task.title}`, error);
        updatedTasks.push(task);
      }
    }
    
    return updatedTasks;
  }

  async syncIssuesToTasks(
    owner: string,
    repo: string
  ): Promise<Task[]> {
    logger.info(`Syncing issues from ${owner}/${repo}`);
    
    try {
      const issues = await this.client.listIssues(owner, repo);
      
      const tasks: Task[] = issues.map(issue => ({
        id: `task-${issue.number}`,
        title: issue.title,
        description: issue.body || '',
        status: this.mapIssueStateToTaskStatus(issue.state),
        githubIssueId: issue.number
      }));
      
      logger.info(`Synced ${tasks.length} issues to tasks`);
      return tasks;
    } catch (error) {
      logger.error('Failed to sync issues to tasks', error);
      return [];
    }
  }

  async updateTaskStatus(
    owner: string,
    repo: string,
    task: Task
  ): Promise<void> {
    if (!task.githubIssueId) {
      logger.warn(`Task ${task.id} has no associated GitHub issue`);
      return;
    }
    
    const state = this.mapTaskStatusToIssueState(task.status);
    
    try {
      await this.client.updateIssue(owner, repo, task.githubIssueId, { state });
      logger.info(`Updated issue #${task.githubIssueId} to ${state}`);
    } catch (error) {
      logger.error(`Failed to update issue #${task.githubIssueId}`, error);
    }
  }

  private formatTaskBody(task: Task, spec: Spec): string {
    return `## Description
${task.description}

## From Spec
**Spec:** ${spec.title}

**Task ID:** ${task.id}

---
*Generated by Swarm CLI*`;
  }

  private mapIssueStateToTaskStatus(state: string): 'pending' | 'in_progress' | 'completed' {
    switch (state) {
      case 'open':
        return 'pending';
      case 'closed':
        return 'completed';
      default:
        return 'pending';
    }
  }

  private mapTaskStatusToIssueState(status: string): 'open' | 'closed' {
    switch (status) {
      case 'completed':
        return 'closed';
      case 'pending':
      case 'in_progress':
      default:
        return 'open';
    }
  }
}
